name: "Maven MultiModule Dependency Submission"
on:
  push:
    branches: [ "main" ]
jobs:
  tree:
    name: Maven Multi Dependency Submission
    runs-on: ubuntu-20.04
 
    permissions:
      actions: read
      contents: write
      
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - run: mvn --version
  
        
    - name: Submit Web Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@multi-module
